Performance improvements and new operators
fsprojects/FSharp.Data.Adaptive pull request #118
Opened 2024-10-07 15:11 UTC by luithefirst

I have implemented some improvements and new specialized operators. They should not expose any breaking changes. Here are the preliminary release notes:

- added ASet.ofListTree and ASet.ofSetTree
- added AList.mapToASet
- added AMap.ofASetMapped/ofASetMappedIgnoreDuplicates (optimized ASet.groupBy)
- added MapNode/SetNode addInPlace helpers
- added SetNode.head
- added special implementation for ASet.filterA
- added special implementation for ASet.union with one set constant
- improved AList.append
- changed internal tuples/options to value types
- changed Index garbage collection to run in finalizer
- preferred using struct enumerators
- avoided using active patterns to match set operations
- updated to net 8.0
- updated Aardvark.Build and aardpack to 2.0.2
- updated Fable to 4.22.0
- fixed race condition in Index

Benchmarks in my application showed that reducing the GC load (by using value options/tuples and struct enumerators) results in a noticeable performance improvement (5-10%). It also needs to be considered that benchmarks are typically quite isolated and do not represent typical system loads. In real environments, there might be much more concurrent activity and the CPU cache and GC might be more busy. In those cases, I expect an even bigger impact.

I will create a preview release package next. Please review the changes and drop your comments below ;-)

Further notes: 
- using struct enumerators cannot elegantly be combined with in-place construction of map/list deltas (should be used if possible), better pattern possible?
- in-place construction of HashSetDelta also possible? (significant overhead when building up large deltas immutable)
- add choose/chooseA operators with value options -> chooseV and choseAV/chooseVA or what?
- need help testing Fable
- FSharp.Data.Adaptive needs the net 8.0 target for Trimming
- FSharp.Core dependency is untouched.  Form my tests it appears sufficient that the target application uses the latest version.

2024-10-10 17:50 UTC, krauthaufen commented
Looks good, can in break any existing code?

2024-10-15 16:02 UTC, luithefirst commented
I did not intend to introduce any breaking changes, but due to the amount of changes, I would be more careful and want to run more tests in other projects. It would also be nice if you could put this to a test in one of your applications.

I also just checked out two older versions of my program and ran some benchmarks:

```
| Method                  | IterationCount | Mean       | Error    | StdDev   | Gen0        | Gen1        | Gen2      | Allocated  |
|------------------------ |--------------- |-----------:|---------:|---------:|------------:|------------:|----------:|-----------:|-----------------------------------------------------------------
| VisibleGeometriesBuild  | 10             |   296.0 ms | 11.30 ms |  6.72 ms |  25000.0000 |   7000.0000 |         - |  411.49 MB | ASet.filterA + Ag
| BuildRenderableSubsets  | 10             | 1,285.0 ms | 37.74 ms | 24.97 ms |  42000.0000 |  22000.0000 |         - |  688.55 MB | ASet.collect + AVal.bind
| BuildGroupedRenderables | 10             | 1,407.9 ms | 43.27 ms | 28.62 ms |  34000.0000 |  16000.0000 |         - |   576.9 MB | ASet.chooseA + ASet.filterA + AVal.bind + AVal.map + ASet.union
| EntitySetBuild          | 20             |   309.2 ms |  6.35 ms |  7.32 ms |  13000.0000 |   6000.0000 |         - |  217.84 MB | ASet.collect + ASet.union + ASet.bind + ASet.choose
| InstanceTreeBuild       | 20             | 4,887.6 ms | 26.70 ms | 30.75 ms | 134000.0000 | 115000.0000 | 1000.0000 | 2396.42 MB | AList.collect + AList.bind + AList.concat + AList.chooseA + Ag
| NodeIdMapBuild          | 20             |   672.6 ms |  6.60 ms |  7.34 ms |  11000.0000 |   6000.0000 |         - |  198.85 MB | ASet.map + AMap.ofASetIgnoreDuplicates (explicit)
| NodeEntityMapBuild      | 20             |   267.3 ms |  3.39 ms |  3.63 ms |   8000.0000 |   5000.0000 |         - |  136.38 MB | ASet.groupBy (ASet.map + AMap.ofASet) (explicit)

FSharp.Data.Adaptive 1.2.17-prerelease0001
| Method                  | IterationCount | Mean        | Error     | StdDev    | Gen0        | Gen1        | Gen2      | Allocated |
|------------------------ |--------------- |------------:|----------:|----------:|------------:|------------:|----------:|----------:|
| VisibleGeometriesBuild  | 10             |   118.40 ms |  2.301 ms |  1.369 ms |   3000.0000 |   1000.0000 |         - |  65.55 MB | new ASet.filterA
| BuildRenderableSubsets  | 10             | 1,029.78 ms | 22.195 ms | 14.681 ms |  21000.0000 |  20000.0000 |         - | 354.12 MB |
| BuildGroupedRenderables | 10             | 1,007.02 ms |  7.174 ms |  3.752 ms |  13000.0000 |  12000.0000 |         - | 237.57 MB |
| EntitySetBuild          | 20             |   270.35 ms |  6.089 ms |  7.012 ms |  11000.0000 |   7000.0000 |         - | 185.13 MB |
| InstanceTreeBuild       | 20             | 4,341.76 ms | 15.867 ms | 18.272 ms | 102000.0000 | 101000.0000 | 1000.0000 | 1913.5 MB |
| NodeIdMapBuild          | 20             |   647.60 ms |  5.785 ms |  6.190 ms |  10000.0000 |   6000.0000 |         - | 179.36 MB |
| NodeEntityMapBuild      | 20             |    65.74 ms |  1.219 ms |  1.404 ms |   1000.0000 |   1000.0000 |         - |  31.04 MB | new ASet.groupBy
```

More optimization on the application side (e.g. no longer using Ag):
```
| Method                  | IterationCount | Mean       | Error    | StdDev   | Gen0       | Gen1       | Gen2      | Allocated  |
|------------------------ |--------------- |-----------:|---------:|---------:|-----------:|-----------:|----------:|-----------:|
| VisibleGeometriesBuild  | 10             |   172.4 ms |  5.56 ms |  2.91 ms | 14000.0000 |  5000.0000 |         - |  240.16 MB | no more Ag
| BuildRenderableSubsets  | 10             |   916.5 ms | 34.22 ms | 22.64 ms | 31000.0000 | 21000.0000 |         - |  519.74 MB |
| BuildGroupedRenderables | 10             | 1,135.9 ms | 26.94 ms | 14.09 ms | 24000.0000 | 14000.0000 |         - |  414.52 MB |
| EntitySetBuild          | 20             |   242.1 ms |  6.34 ms |  7.30 ms | 11000.0000 |  5000.0000 |         - |  187.99 MB |
| InstanceTreeBuild       | 20             | 2,596.7 ms | 12.18 ms | 13.53 ms | 86000.0000 | 75000.0000 | 1000.0000 | 1358.61 MB | no more Ag
| NodeIdMapBuild          | 20             |   519.9 ms |  6.34 ms |  7.30 ms | 10000.0000 |  6000.0000 |         - |  182.67 MB | shorter node Ids
| NodeEntityMapBuild      | 20             |   234.2 ms |  3.50 ms |  4.03 ms |  8000.0000 |  5000.0000 |         - |  136.52 MB |

FSharp.Data.Adaptive 1.2.17-prerelease0001
| Method                  | IterationCount | Mean        | Error     | StdDev    | Gen0       | Gen1       | Gen2      | Allocated  |
|------------------------ |--------------- |------------:|----------:|----------:|-----------:|-----------:|----------:|-----------:|
| VisibleGeometriesBuild  | 10             |    68.11 ms |  4.376 ms |  2.895 ms |  2000.0000 |  1000.0000 |         - |   49.46 MB |
| BuildRenderableSubsets  | 10             |   834.10 ms | 23.657 ms | 15.647 ms | 20000.0000 | 19000.0000 |         - |  334.76 MB |
| BuildGroupedRenderables | 10             |   947.64 ms | 43.531 ms | 28.793 ms | 13000.0000 | 12000.0000 |         - |  237.63 MB |
| EntitySetBuild          | 20             |   216.58 ms |  4.598 ms |  5.295 ms |  9000.0000 |  4000.0000 |         - |  157.52 MB |
| InstanceTreeBuild       | 20             | 2,193.04 ms | 14.644 ms | 16.864 ms | 66000.0000 | 65000.0000 | 1000.0000 | 1038.17 MB |
| NodeIdMapBuild          | 20             |   478.65 ms |  5.416 ms |  6.237 ms |  9000.0000 |  5000.0000 |         - |  163.19 MB |
| NodeEntityMapBuild      | 20             |    62.00 ms |  1.724 ms |  1.985 ms |  1000.0000 |          - |         - |   31.05 MB |
```

Latest application version using all new adaptive operators:
```
| Method                  | IterationCount | Mean      | Error     | StdDev    | Gen0       | Gen1       | Allocated |
|------------------------ |--------------- |----------:|----------:|----------:|-----------:|-----------:|----------:|
| VisibleGeometriesBuild  | 10             |  64.05 ms |  3.175 ms |  2.100 ms |  2000.0000 |  1000.0000 |  49.47 MB | ASet.filterA
| BuildRenderableSubsets  | 10             | 681.86 ms | 15.597 ms | 10.317 ms | 20000.0000 | 19000.0000 | 335.27 MB |
| BuildGroupedRenderables | 10             | 556.07 ms | 12.748 ms |  6.667 ms |  8000.0000 |  7000.0000 | 162.37 MB |
| EntitySetBuild          | 20             |  64.91 ms |  0.929 ms |  1.070 ms |  2000.0000 |  1000.0000 |  39.79 MB | ASet.ofSetTree
| InstanceTreeBuild       | 20             | 790.49 ms | 19.553 ms | 22.517 ms | 26000.0000 | 25000.0000 | 428.78 MB | ASet.ofListTree
| NodeIdMapBuild          | 20             | 226.08 ms | 14.224 ms | 16.380 ms |  3000.0000 |  2000.0000 |  68.46 MB | AMap.ofASetMappedIgnoreDuplicates
| NodeEntityMapBuild      | 20             |  65.78 ms |  2.113 ms |  2.434 ms |  1000.0000 |          - |  31.04 MB | ASet.groupBy
```

2025-02-17 16:19 UTC, hyazinthh requested changes
Looks good overall, the breaking change should probably be reverted.

2025-02-17 16:22 UTC, luithefirst commented on src/CSharp.Data.Adaptive/ASet.fs
> -    static member MapToMap(this: aset<'T>, mapping: Func<'T, 'Value>) =
I was unaware that this is a breaking change, let's revert it.

2025-02-17 16:28 UTC, luithefirst commented on src/FSharp.Data.Adaptive/AdaptiveHashMap/AdaptiveHashMap.fs
> +                if d.Count = 1 then // >= 1 ??
Yes, the correct translation would be `>0` and `else`, however, the changes consumed from an `aset` (of in our implementation) can only ever be 1 or -1. If the `Count` would be truly arbitrary, we would need proper counting that can handle this, so I decided it is better to throw an exception, similar to other similar places.

2025-02-17 16:39 UTC, hyazinthh commented on src/CSharp.Data.Adaptive/ASet.fs
> -    static member MapToMap(this: aset<'T>, mapping: Func<'T, 'Value>) =
Reverted

2025-02-17 16:46 UTC, merged